# Define main configuration paths
export CONFIG_HOME="$HOME/.config"
export DOTFILES="$HOME/.dot"

# Determine current profile and set DOT_PROFILE_PATH
DOT_PROFILE="${$(cat "$HOME/.dot_profile" 2>/dev/null):-default}"
export DOT_PROFILE_PATH="$DOTFILES/profiles/$DOT_PROFILE"

# Load environment secrets and vars
[ -f "$HOME/.env" ] && source "$HOME/.env"
[ -f "$DOTFILES/zsh/env.zsh" ] && source "$DOTFILES/zsh/env.zsh"
[ -f "$DOT_PROFILE_PATH/env.zsh" ] && source "$DOT_PROFILE_PATH/env.zsh"

# Use Vim as pager for manpages
export MANPAGER="vim +Man!"
